[server]
maxUploadSize = 4096

[theme]
# Primary accent for interactive elements
primaryColor = '#2AD5CE'

# Background color for the main content area
backgroundColor = '#320080'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#6908FF'

# Color used for almost all text
textColor = '#FFFFFF'